name: coord_translator
description: A flutter application to convert .

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 1.0.0 - initial release
# 1.1.3 - added what3words section
# 1.1.4 - migrated to null safety with Dart 1.12
# 1.1.5 - fixed issue concerning fields not clearing properly when user switched lat and long format after conversion. changed from using snackbars to toasts when user copies a field.
# 1.2.0 - added settings menu that allows users to change their desired lat/long and grid ref formats so the values will appear in this format whenever the app loads
# 1.2.1 - changed grid reference input for numerical references to be separated by a space rather than a comma
# 1.2.2 - fixed issue with what3words section not working on release
# 1.2.3 - updated what3words logo and removed lines under output values
# 1.2.4 - added option to turn off what3words output
# 1.2.5 - redesigned settings menu and added more functionality for output formatting
# 1.2.6 - bug fixes
# 1.2.7 - added dark mode in settings menu
# 1.2.8 - fixed bugs with dark mode
version: 1.2.8+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.1.1
  latlong_to_osgrid: ^1.3.2
  path_provider: ^2.0.1
  pull_to_refresh: ^1.6.4
  url_launcher: ^6.0.3
  image_picker: ^0.7.3
  path: ^1.7.0
  what3words: ^3.1.0
  flutter_local_notifications: ^5.0.0
  fluttertoast: ^8.0.3
  dynamic_themes: ^1.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launchIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/w3wlogo.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
